Fix Make
diegstroyer/oneDrive pull request #2
Opened 2022-11-11 10:57 UTC by spbisc97

Translate and Add Make description

2022-11-17 18:22 UTC, diegstroyer requested changes

2022-11-17 18:22 UTC, diegstroyer commented on Makefile
> +# lg - Extansion lg manager, run ALT+F2
Should be Extension, not Extansion

2022-11-17 22:42 UTC, spbisc97 commented
should be fixed! Thanks!

2022-11-18 09:54 UTC, diegstroyer approved these changes

2022-11-18 09:54 UTC, merged